### ISSUE TITLE
Adding new NPCs

### ISSUE THREAD

**Issue by selsie** [alsa64/NpcProtector#4]
Hallo alsa64,

Ich würde mich freuen, wenn es die Möglichkeit gäbe Einstellungen zu machen, welche weiteren NPCs geschützt werden sollen. Danke im Voraus

**Comment by alsa64** [comment]
Has been implemented in #5

**Comment by selsie** [comment]
I added a new NPC to protect and clicked the + twice. Now the name is entered twice in the list. Could you make a function to prevent duplicates or to permit deletion as well?
The new settings make things much easier! Thank you.

**Comment by alsa64** [comment]
I'm not sure if this is possible. The settings integration has been added as a PR #5 by another GitHub user. Looking at the code, it seems to be entirely generated by Synthesis itself, so this looks like something only Synthesis could change. In the meantime, you can just edit the `settings.json` file to remove the NPCs you have added twice. If there's a good reason to flag an NPC as protected, you can also fork the repository, add them and make a PR and it would become the default for everyone.

**Comment by selsie** [comment]
To delete a NPC I edited the settings file, but now discovered that the tiny "Backspace" icon deletes the selected NPCs from the list. Who would have guessed.
